Feat: adiciona conteúdo da Simara Conceição - quero ser dev
ComunidadeCafeina/women-teaching-tech pull request #89
Opened 2022-10-08 21:25 UTC by malufell

Adiciona o conteúdo da Simara Conceição: canal do youtube e podcast 'quero ser dev'.

2022-10-20 11:49 UTC, BiancaPereira approved these changes
Obrigada pela contribuição!

2022-10-20 11:50 UTC, BiancaPereira requested changes
Oii, o seu PR está com conflito, poderia verificar? Se precisar de ajuda pra arrumar me avisa!

2022-10-21 13:58 UTC, malufell commented
Oii @BiancaPereira, fiz agora um sync no repo e não vejo conflito, parece estar ok com a msg `This branch has no conflicts with the base branch`. Qualquer coisa me avisa? Ainda estou aprendendo a trabalhar com fork :sweat_smile:

2022-10-24 12:54 UTC, BiancaPereira approved these changes
Oii, que estranho ahaha Aprovado aqui, obrigada!

2022-10-24 12:54 UTC, merged